name: Work Stats

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"
  
jobs:
  update:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
    - uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
